modLoader="javafml"
loaderVersion="[26,)"
license="All Rights Reserved"
authors="Example Author"
displayName="Chaotic Sheep"

[[mods]]
modId="chaoticsheep"
version="1.0.0"
displayName="Chaotic Sheep"
logoFile="examplelogo.png"
credits="Created with NeoForge"
authors="Example Author"
description='''
Chaotic Sheep is a mod that adds chaos to your world! 
Kill a sheep and there's a 1% chance that a wither will spawn.
Good luck!
'''
displayURL="https://example.com"
logoFile="examplelogo.png"
