modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="chaoticsheep"
version="1.0.0"
displayName="Chaotic Sheep"
authors="Austin Moser"
description='''Spawns a wither with a 1% chance when you kill a sheep. Good luck.'''

[[dependencies.chaoticsheep]]
modId="neoforge"
type="required"
versionRange="[26.1.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaoticsheep]]
modId="minecraft"
type="required"
versionRange="[26.1.2,26.2)"
ordering="NONE"
side="BOTH"
